on: push
env:
  REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
  REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    environment: dev
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_GOOGLE_API_KEY=${{ secrets.REACT_APP_GOOGLE_API_KEY }} >> .env
          echo REACT_APP_URL=${{ secrets.REACT_APP_URL }} >> .env
      - run: npm run build --if-present
